[package]
name = "widgets"
version.workspace = true
edition.workspace = true

[dependencies]
makepad-widgets.workspace = true
makepad-component.workspace = true
cpal.workspace = true
parking_lot.workspace = true
log.workspace = true
crossbeam-channel.workspace = true
